### ISSUE TITLE
Separate fonts repos

### ISSUE THREAD

**Issue by davelab6** [Microsoft/fonts#7]
I suggest having one repo per font project, and using this repo to index them, such as with git submodules, or just links in the readme (eg http://github.com/itfoundry/hindkit) 

This is because when you tag a release for one font family, it will include the entire repo at that stage, which may be a non-release-ready version of another family, or at least make the automatic release ZIPs full with other projects. 

(The http://github.com/google/fonts repo isn't ideal, because it also has (100s of) projects all in 1 repo, but that is a 'downstream' repo, not the 'upstream' where the fonts are developed. For the upstream repos that don't have a home in the designer's own Github account/org, there is http://github.com/googlefonts :) 

So perhaps a "microsoft-fonts" Github organization could be good.

A short-term suggestion is to move the license file from the root into each project's directory, since the current LICENSE file in the root has Selawick declared as an RFN and trademark, which appears to apply to the whole repo.

**Comment by aaronbell** [comment]
OK, I've moved the Selawik source files off to their own repo and this one is more acting as an Indexing now. The Win-JS issue is a bit of a question, though, since there aren't really source files for those. As such, I'm tempted to just leave them here as a special casing. 

Doesn't seem like there's a way to set up a "microsoft-fonts" org right now, so everything lives in the same Microsoft group.

**Comment by davelab6** [comment]
:+1:
